version: "3"

networks:
  netA:
    ipam:
      driver: default
      config:
        - subnet: 10.0.10.0/24

  netB:
    ipam:
      driver: default
      config:
        - subnet: 10.0.11.0/24

  net1:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24

  net2:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24

  net3:
    ipam:
      driver: default
      config:
        - subnet: 10.0.3.0/24

  net4:
    ipam:
      driver: default
      config:
        - subnet: 10.0.4.0/24

services:
  ha:
    build:
      context: .
      dockerfile: Dockerfile-h
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      netA:
        ipv4_address: 10.0.10.10   

  hb:
    build:
      context: .
      dockerfile: Dockerfile-h
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      netB:
        ipv4_address: 10.0.11.11    

  r1:
    build:
      context: .
      dockerfile: Dockerfile-r1
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      netA:
        ipv4_address: 10.0.10.3
      net1:
      net4:
