version: "3"

networks:
  netA:
    ipam:
      driver: default
      config:
        - subnet: 10.0.10.0/24

  netB:
    ipam:
      driver: default
      config:
        - subnet: 10.0.11.0/24

services:
  ha:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      netA:
        ipv4_address: 10.0.10.10   

  hb:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      netB:
        ipv4_address: 10.0.11.11    

  r1:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      netA:
        ipv4_address: 10.0.10.3
      netB:
        ipv4_address: 10.0.11.3
    
